// import { PricedProduct } from "@medusajs/medusa/dist/types/pricing"
// import { NextPage } from "next"
// import { AppProps } from "next/app"
// import { ReactElement, ReactNode } from "react"

export interface Billboard {
    id: string,
    label: string,
    imageUrl: string,
};

export interface Category {
    id: string,
    name: string,
    billboards: Billboard[],
}

// export interface Product {
//     variants: any;
//     id: string,
//     title: Category,
//     name: string,
//     price: string,
//     size: Size;
//     isFeatured: boolean,
//     color: Color,
//     image: any,
// }

// export interface Image {
//     id: string,
//     url: string,
// }

// export interface Color {
//     id: string,
//     name: string,
//     value: string,
// }

// export interface Size {
//     id: string;
//     name: string;
//     value: string;
//   };




// export type CollectionData = {
//   id: string
//   title: string
// }

// export type FeaturedProduct = {
//   id: string// Generated by https://quicktype.io

export interface Types {
  products: Product[];
  count:    number;
  offset:   number;
  limit:    number;
}

export interface Product {
  id:             string;
  title:          string;
  subtitle:       null | string;
  status:         string;
  external_id:    null;
  description:    null | string;
  handle:         string;
  is_giftcard:    boolean;
  discountable:   boolean;
  thumbnail:      string;
  profile_id:     string;
  collection_id:  null;
  type_id:        null;
  weight:         null;
  length:         null;
  height:         null;
  width:          null;
  hs_code:        null;
  origin_country: null;
  mid_code:       null;
  material:       null | string;
  created_at:     string;
  updated_at:     string;
  deleted_at:     null;
  metadata:       Metadata | null;
  variants:       Variant[];
  options:        Option[];
  images:         Image[];
  tags:           any[];
  collection:     null;
  type:           null;
}

export interface Image {
  id:         string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  url:        string;
  metadata:   null;
}

export interface Metadata {
  size:  string;
  color: string;
}

export interface Option {
  id:         string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  title:      string;
  product_id: string;
  metadata:   null;
  values:     any[];
}

export interface Variant {
  id:                        string;
  created_at:                string;
  updated_at:                string;
  deleted_at:                null;
  title:                     string;
  product_id:                string;
  sku:                       null;
  barcode:                   null;
  ean:                       null;
  upc:                       null;
  variant_rank:              number;
  inventory_quantity:        number;
  allow_backorder:           boolean;
  manage_inventory:          boolean;
  hs_code:                   null;
  origin_country:            null;
  mid_code:                  null;
  material:                  null;
  weight:                    null;
  length:                    null;
  height:                    null;
  width:                     null;
  metadata:                  Metadata;
  prices:                    Price[];
  options:                   any[];
  original_price:            null;
  calculated_price:          null;
  original_price_incl_tax:   null;
  calculated_price_incl_tax: null;
  original_tax:              null;
  calculated_tax:            null;
  tax_rates:                 null;
}

export interface Price {
  id:            string;
  created_at:    string;
  updated_at:    string;
  deleted_at:    null;
  currency_code: string;
  amount:        number;
  min_quantity:  null;
  max_quantity:  null;
  price_list_id: null;
  variant_id:    string;
  region_id:     null;
  price_list:    null;
}

//   title: string
//   handle: string
//   thumbnail?: string
// }

// export type StoreNavData = {
//   collections: CollectionData[]
//   hasMoreCollections: boolean
//   featuredProducts: PricedProduct[]
// }

// /vercel\.app$/



